"""Primera Migracion

Revision ID: 41ef7bcde10b
Revises: c76ce27486f6
Create Date: 2026-02-25 20:29:58.221476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41ef7bcde10b'
down_revision = 'c76ce27486f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=200), nullable=True))
        batch_op.drop_column('apaterno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apaterno', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
